trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "This is a demo YAML file for DevSecOps Pipeline"
  displayName: "Print Console Text for Demo"
  
- script: |
    mvn clean package
  displayName: "Building Azure DevOps App"

- script: |
    mvn clean test
  displayName: "Testing Azure DevOps App"
